version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tasks
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    ports:
      - 3000:3000
    networks:
      - web
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm start

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  test:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tasks
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - .:/usr/src/app
    command: npm test
    depends_on:
      - db
      - app

networks:
  web:
    driver: bridge
